server:
  port: 8096

spring:
  datasource:
    url: jdbc:h2:file:./data/moneportdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa: # 혹시 JPA 병행 테스트 시 필요
    hibernate:
      ddl-auto: none
    show-sql: true

mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  type-aliases-package: com.moneport.backend.domain

logging:
  level:
    com.moneport: DEBUG
    org.mybatis: DEBUG

# 스웨거
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
    tagsSorter: alpha

#jwt
jwt:
  secret: uH5NdqVcK4F9gC7XsT8JwM9qZyL4eP6r
  expiration: 3600000 # 1시간 (밀리초)